Feature/merge im 2.13.1 to im master
intermedia-net/pjproject pull request #36
Opened 2023-11-16 14:35 UTC by esmitenko-intermedia

Conflicts:
	.github/workflows/ccpp.yml
	.github/workflows/ci-android.yml
	pjlib/include/pj/config.h
	pjlib/src/pj/ssl_sock_imp_common.c
	pjmedia/src/pjmedia/codec.c
	pjmedia/src/pjmedia/stream.c
	pjmedia/src/pjmedia/vid_conf.c
	pjsip/src/pjsua-lib/pjsua_aud.c
	pjsip/src/pjsua-lib/pjsua_call.c
	version.mak

2023-11-17 08:32 UTC, dshamaev-intermedia commented on pjmedia/src/pjmedia/stream.c
> +        int i;
in C we need either to move declaration to the top to improve compatibility with compilers(it's c++ feature to be able to declare variables at any line in func and not at top) or we could declare "i" in for loop
for (int i = 1; i < (seq_st.diff - 1); ++i) {

2023-11-17 08:40 UTC, dshamaev-intermedia requested changes

2023-11-17 08:40 UTC, dshamaev-intermedia commented on pjmedia/src/pjmedia/stream.c
> +        int i;
in C we need either to move declaration to the top to improve compatibility with compilers(it's c++ feature to be able to declare variables at any line in func and not at top) or we could declare "i" in for loop
for (int i = 1; i < (seq_st.diff - 1); ++i) {

2023-11-20 08:08 UTC, dshamaev-intermedia approved these changes

2023-11-20 16:00 UTC, inekrasov-intermedia approved these changes

2023-11-20 16:35 UTC, anikitin-intermedia approved these changes

2023-11-21 14:31 UTC, merged